# Generated by Django 2.0.5 on 2018-05-28 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_level', models.IntegerField(blank=True, null=True)),
                ('teacher_name', models.CharField(blank=True, max_length=20, null=True)),
                ('assistant_name', models.CharField(blank=True, max_length=20, null=True)),
                ('skype_count', models.IntegerField(blank=True, null=True)),
                ('skype_count_now', models.IntegerField(blank=True, null=True)),
                ('type', models.CharField(blank=True, max_length=128, null=True)),
                ('if_protocol', models.IntegerField(blank=True, null=True)),
                ('create_time', models.DateTimeField(blank=True, null=True)),
                ('update_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-create_time', '-update_time'],
                'db_table': 'lesson',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=11, null=True)),
                ('if_old_major', models.IntegerField(blank=True, null=True)),
                ('sex', models.IntegerField(blank=True, null=True)),
                ('mobile', models.CharField(blank=True, max_length=11, null=True)),
                ('qq', models.CharField(blank=True, max_length=11, null=True, unique=True)),
                ('adviser', models.CharField(blank=True, max_length=20, null=True)),
                ('due_year', models.CharField(blank=True, max_length=128, null=True)),
                ('old_school', models.CharField(blank=True, max_length=20, null=True)),
                ('old_major', models.CharField(blank=True, max_length=20, null=True)),
                ('study_status', models.IntegerField(blank=True, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('apply_time', models.CharField(blank=True, max_length=20, null=True)),
                ('source', models.CharField(blank=True, max_length=20, null=True)),
                ('background', models.CharField(blank=True, max_length=11, null=True)),
                ('qq_group', models.IntegerField(blank=True, null=True)),
                ('author', models.CharField(blank=True, max_length=20, null=True)),
                ('remark', models.TextField(blank=True, null=True)),
                ('extend', models.TextField(blank=True, null=True)),
                ('email_sent', models.BooleanField(default=False)),
                ('major_sent', models.IntegerField(blank=True, null=True)),
                ('public_sent', models.IntegerField(blank=True, null=True)),
                ('order_style', models.IntegerField(blank=True, null=True)),
                ('target_school', models.CharField(blank=True, max_length=20, null=True)),
                ('create_time', models.DateTimeField(auto_now=True, null=True)),
                ('update_time', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'ordering': ['-create_time', '-update_time'],
                'managed': True,
                'db_table': 'student',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=11, null=True)),
                ('sex', models.IntegerField(blank=True, null=True)),
                ('mobile', models.CharField(blank=True, max_length=11, null=True)),
                ('qq', models.CharField(blank=True, max_length=11, null=True)),
                ('idcard', models.CharField(blank=True, max_length=128, null=True)),
                ('bank_number', models.CharField(blank=True, max_length=20, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=20, null=True)),
                ('job', models.CharField(blank=True, max_length=11, null=True)),
                ('bachelor_school', models.CharField(blank=True, max_length=20, null=True)),
                ('bachelor_major', models.CharField(blank=True, max_length=20, null=True)),
                ('fudao_school', models.CharField(blank=True, max_length=20, null=True)),
                ('school_312', models.CharField(blank=True, max_length=20, null=True)),
                ('is_war_more', models.BooleanField(default=False)),
                ('is_cross_major', models.BooleanField(default=False)),
                ('is_wokring', models.BooleanField(default=False)),
                ('is_passed', models.BooleanField(default=True)),
                ('passed_type', models.CharField(blank=True, max_length=20, null=True)),
                ('join_year', models.CharField(blank=True, max_length=20, null=True)),
                ('study_year', models.CharField(blank=True, max_length=20, null=True)),
                ('study_type', models.CharField(blank=True, max_length=20, null=True)),
                ('first_total', models.IntegerField(blank=True, null=True)),
                ('pro_class_score', models.IntegerField(blank=True, null=True)),
                ('english_class_score', models.IntegerField(blank=True, null=True)),
                ('politic_class_score', models.IntegerField(blank=True, null=True)),
                ('first_rank', models.IntegerField(blank=True, null=True)),
                ('second_rand', models.IntegerField(blank=True, null=True)),
                ('final_rank', models.IntegerField(blank=True, null=True)),
                ('is_stay', models.BooleanField(default=True)),
                ('bidth', models.CharField(blank=True, max_length=20, null=True)),
                ('is_zhinanqun', models.BooleanField(default=True)),
                ('is_fudaogongzuoqun', models.BooleanField(default=True)),
                ('is_weixunqun', models.BooleanField(default=True)),
                ('is_xieyi_send', models.BooleanField(default=True)),
                ('is_xieyi_back', models.BooleanField(default=True)),
                ('is_xiaoqugroup', models.BooleanField(default=True)),
                ('train_records', models.TextField(blank=True, null=True)),
                ('remark', models.TextField(blank=True, null=True)),
                ('create_time', models.DateTimeField(auto_now=True, null=True)),
                ('update_time', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'ordering': ['-create_time', '-update_time'],
                'managed': True,
                'db_table': 'teacher',
            },
        ),
        migrations.AddField(
            model_name='student',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ky.Teacher'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ky.Student'),
        ),
    ]
