# Generated by Django 2.0.5 on 2018-05-13 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OiClassCommon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_level', models.IntegerField(blank=True, null=True)),
                ('teacher_name', models.CharField(blank=True, max_length=20, null=True)),
                ('assistant_name', models.CharField(blank=True, max_length=20, null=True)),
                ('skype_count', models.IntegerField(blank=True, null=True)),
                ('skype_count_now', models.IntegerField(blank=True, null=True)),
                ('fee', models.IntegerField(blank=True, null=True)),
                ('create_time', models.DateTimeField(blank=True, null=True)),
                ('update_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'oi_class_common',
            },
        ),
        migrations.CreateModel(
            name='OiClassCommonEnglish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_level', models.IntegerField(blank=True, null=True)),
                ('teacher_name', models.CharField(blank=True, max_length=20, null=True)),
                ('assistant_name', models.CharField(blank=True, max_length=20, null=True)),
                ('skype_count', models.IntegerField(blank=True, null=True)),
                ('skype_count_now', models.IntegerField(blank=True, null=True)),
                ('fee', models.IntegerField(blank=True, null=True)),
                ('if_protocol', models.IntegerField(blank=True, null=True)),
                ('create_time', models.DateTimeField(blank=True, null=True)),
                ('update_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'oi_class_common_english',
            },
        ),
        migrations.CreateModel(
            name='OiClassCommonPolitic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_level', models.IntegerField(blank=True, null=True)),
                ('teacher_name', models.CharField(blank=True, max_length=20, null=True)),
                ('assistant_name', models.CharField(blank=True, max_length=20, null=True)),
                ('skype_count', models.IntegerField(blank=True, null=True)),
                ('skype_count_now', models.IntegerField(blank=True, null=True)),
                ('fee', models.IntegerField(blank=True, null=True)),
                ('if_protocol', models.IntegerField(blank=True, null=True)),
                ('create_time', models.DateTimeField(blank=True, null=True)),
                ('update_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'oi_class_common_politic',
            },
        ),
        migrations.CreateModel(
            name='OiClassProfessional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_level', models.IntegerField(blank=True, null=True)),
                ('teacher_name', models.CharField(blank=True, max_length=20, null=True)),
                ('assistant_name', models.CharField(blank=True, max_length=20, null=True)),
                ('skype_count', models.IntegerField(blank=True, null=True)),
                ('skype_count_now', models.IntegerField(blank=True, null=True)),
                ('fee', models.IntegerField(blank=True, null=True)),
                ('if_protocol', models.IntegerField(blank=True, null=True)),
                ('create_time', models.DateTimeField(blank=True, null=True)),
                ('update_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'oi_class_professional',
            },
        ),
        migrations.CreateModel(
            name='OiOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_style', models.IntegerField(blank=True, null=True)),
                ('target_school', models.CharField(blank=True, max_length=20, null=True)),
                ('target_major', models.CharField(blank=True, max_length=20, null=True)),
                ('create_time', models.DateTimeField(auto_now=True, null=True)),
                ('update_time', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'ordering': ['-create_time', '-update_time'],
                'db_table': 'oi_order',
            },
        ),
        migrations.CreateModel(
            name='UiStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=11, null=True)),
                ('if_old_major', models.IntegerField(blank=True, null=True)),
                ('sex', models.IntegerField(blank=True, null=True)),
                ('mobile', models.CharField(blank=True, max_length=11, null=True)),
                ('qq', models.CharField(blank=True, max_length=11, null=True, unique=True)),
                ('adviser', models.CharField(blank=True, max_length=20, null=True)),
                ('due_year', models.CharField(blank=True, max_length=128, null=True)),
                ('old_school', models.CharField(blank=True, max_length=20, null=True)),
                ('old_major', models.CharField(blank=True, max_length=20, null=True)),
                ('study_status', models.IntegerField(blank=True, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('apply_time', models.CharField(blank=True, max_length=20, null=True)),
                ('source', models.CharField(blank=True, max_length=20, null=True)),
                ('background', models.CharField(blank=True, max_length=11, null=True)),
                ('qq_group', models.IntegerField(blank=True, null=True)),
                ('author', models.CharField(blank=True, max_length=20, null=True)),
                ('remark', models.TextField(blank=True, null=True)),
                ('extend', models.TextField(blank=True, null=True)),
                ('create_time', models.DateTimeField(auto_now=True, null=True)),
                ('update_time', models.DateTimeField(auto_now=True, null=True)),
                ('email_sent', models.BooleanField(default=False)),
                ('major_sent', models.IntegerField(blank=True, null=True)),
                ('public_sent', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-create_time', '-update_time'],
                'db_table': 'ui_student',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UiTeacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=11, null=True)),
                ('sex', models.IntegerField(blank=True, null=True)),
                ('mobile', models.CharField(blank=True, max_length=11, null=True)),
                ('qq', models.CharField(blank=True, max_length=11, null=True)),
                ('job', models.CharField(blank=True, max_length=11, null=True)),
                ('course', models.CharField(blank=True, max_length=30, null=True)),
                ('guide_type', models.IntegerField(blank=True, null=True)),
                ('birth_date', models.CharField(blank=True, max_length=10, null=True)),
                ('bank_number', models.CharField(blank=True, max_length=20, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=20, null=True)),
                ('bank_branch', models.CharField(blank=True, max_length=20, null=True)),
                ('bachelor_school', models.CharField(blank=True, max_length=20, null=True)),
                ('bachelor_major', models.CharField(blank=True, max_length=20, null=True)),
                ('grade_year', models.IntegerField(blank=True, null=True)),
                ('professional_salary', models.IntegerField(blank=True, null=True)),
                ('open_class_salary', models.IntegerField(blank=True, null=True)),
                ('one_to_one_salary', models.IntegerField(blank=True, null=True)),
                ('other_salary', models.IntegerField(blank=True, null=True)),
                ('now_school', models.CharField(blank=True, max_length=20, null=True)),
                ('now_major', models.CharField(blank=True, max_length=20, null=True)),
                ('if_pass_direct', models.IntegerField(blank=True, null=True)),
                ('english_class_score', models.IntegerField(blank=True, null=True)),
                ('politic_class_score', models.IntegerField(blank=True, null=True)),
                ('first_rank', models.IntegerField(blank=True, null=True)),
                ('final_rank', models.IntegerField(blank=True, null=True)),
                ('qq_group', models.IntegerField(blank=True, null=True)),
                ('remark', models.TextField(blank=True, null=True)),
                ('extend', models.TextField(blank=True, null=True)),
                ('create_time', models.DateTimeField(auto_now=True, null=True)),
                ('update_time', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'ordering': ['-create_time', '-update_time'],
                'db_table': 'ui_teacher',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='uistudent',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ky.UiTeacher'),
        ),
        migrations.AddField(
            model_name='oiorder',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ky.UiStudent'),
        ),
        migrations.AddField(
            model_name='oiclassprofessional',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ky.OiOrder'),
        ),
        migrations.AddField(
            model_name='oiclasscommonpolitic',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ky.OiOrder'),
        ),
        migrations.AddField(
            model_name='oiclasscommonenglish',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ky.OiOrder'),
        ),
        migrations.AddField(
            model_name='oiclasscommon',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ky.OiOrder'),
        ),
    ]
