# Generated by Django 2.0.2 on 2018-05-27 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ky', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='bank_branch',
            new_name='bidth',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='grade_year',
            new_name='first_total',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='now_major',
            new_name='fudao_school',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='now_school',
            new_name='join_year',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='guide_type',
            new_name='second_rand',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='extend',
            new_name='train_records',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='fee',
        ),
        migrations.RemoveField(
            model_name='student',
            name='target_major',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='course',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='if_pass_direct',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='one_to_one_salary',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='open_class_salary',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='other_salary',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='qq_group',
        ),
        migrations.AddField(
            model_name='teacher',
            name='idcard',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='is_cross_major',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teacher',
            name='is_fudaogongzuoqun',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='is_passed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='is_stay',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='is_war_more',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teacher',
            name='is_weixunqun',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='is_wokring',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teacher',
            name='is_xiaoqugroup',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='is_xieyi_back',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='is_xieyi_send',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='is_zhinanqun',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='passed_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='school_312',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='study_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='study_year',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='type',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
