# Generated by Django 2.0.5 on 2018-05-28 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ky', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='second_rand',
            new_name='second_rank',
        ),
    ]
