# Generated by Django 2.0.5 on 2018-05-28 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ky', '0002_auto_20180528_1641'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='bidth',
            new_name='birth',
        ),
        migrations.AddField(
            model_name='teacher',
            name='second_score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
