# Generated by Django 2.0.5 on 2018-05-29 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ky', '0004_auto_20180529_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='first_rank',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='first_total',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
