# Generated by Django 2.0.5 on 2018-06-07 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ky', '0005_auto_20180529_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='due_year',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='在职或再读'),
        ),
    ]
